### ISSUE TITLE
Script file not actually linked

### ISSUE THREAD

**Issue by aissshah** [fairyaksh/Doogle#35]
Heya! Very cute idea and love the cursors. However, upon reviewing, we couldn't make it work at first. Turns out there is a typo on line 62. The link to the path should either be `script.js` or `./script.js`.

![](https://github.com/fairyaksh/Doogle/blob/master/index.html#L62)

**Comment by fairyaksh** [comment]
Wahh cannot believe it! 😢 😭 

Hopefully you guys all had a chance at looking at it through the live server upon cloning? 

Sorry about this mistake!

All fixed now ✔️

**Comment by aissshah** [comment]
Yup we did! No worries, it happens :smile:
