### ISSUE TITLE
No error state

### ISSUE THREAD

**Issue by jackherizsmith** [fairyaksh/Doogle#44]
Hello, so I searched "chihuahua" and the console tells me there's an error, but the page stays loading. Perhaps you could add to your .catch statement to handle this error?

**Comment by jackherizsmith** [comment]
Have seen the list of dogs, arrayOfBreeds, that misses chihuahua. What are the chances! But also as far as I can see the code never uses that array. What is it for?

**Comment by jessica440** [comment]
it's to display a random result when you click on Doogle (we didn't get that part to work though)
